"""add product category

Revision ID: c5607b273c3e
Revises: ad983105fe7a
Create Date: 2026-03-30 14:48:13.627141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5607b273c3e'
down_revision: Union[str, Sequence[str], None] = 'ad983105fe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=50), server_default='categories', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
